const path = require('path');
const fs = require('fs');
const { dbGet, dbAll, dbRun, dbRaw, testConnection } = require('./services/supabase');

const MIGRATION_FILE = path.join(__dirname, 'database', 'migration.sql');

// Run migration SQL to set up all tables
async function initDatabase() {
  const connected = await testConnection();
  if (!connected) {
    console.error('FATAL: Could not connect to Supabase. Check SUPABASE_DATABASE_URL in .env');
    process.exit(1);
  }

  try {
    const migrationSql = fs.readFileSync(MIGRATION_FILE, 'utf8');
    // Run the entire migration SQL at once
    // PostgreSQL supports multi-statement queries
    try {
      await dbRaw(migrationSql);
    } catch (err) {
      // Ignore "already exists" errors for tables/extensions
      if (!err.message.includes('already exists')) {
        console.warn(`Migration warning: ${err.message}`);
      }
    }

    // Seed mock employer if users table is empty
    const userCount = await dbGet('SELECT COUNT(*) as count FROM users');
    if (parseInt(userCount.count) === 0) {
      console.log('Database empty. Seeding initial data...');
      const bcrypt = require('bcryptjs');
      const defaultPassword = bcrypt.hashSync('Password123!', 10);
      const adminPassword = bcrypt.hashSync('Admin123!', 10);

      await dbRun(
        `INSERT INTO users (email, password, role, name) VALUES ($1, $2, $3, $4)`,
        ['admin@antigravity.com', adminPassword, 'admin', 'Admin']
      );

      const employerResult = await dbRun(
        `INSERT INTO users (email, password, role, name) VALUES ($1, $2, $3, $4) RETURNING id`,
        ['employer@techcorp.com', defaultPassword, 'employer', 'TechCorp Inc.']
      );
      const employerId = employerResult.lastID;

      await dbRun(
        `INSERT INTO profiles (user_id, company_name, company_website, company_bio) VALUES ($1, $2, $3, $4)`,
        [employerId, 'TechCorp Inc.', 'https://techcorp.com', 'TechCorp is a leading innovator in cloud services and enterprise infrastructure products.']
      );

      const mockJobs = [
        {
          title: 'Senior React Developer',
          company: 'TechCorp Inc.',
          location: 'Bangalore, KA (Hybrid)',
          type: 'Full-time',
          experience_level: 'Senior',
          salary: '₹1,02,00,000 - ₹1,27,50,000 / year',
          description: 'TechCorp Inc. is a Bangalore-based enterprise SaaS company that builds next-generation infrastructure monitoring and analytics platforms for Fortune 500 clients. Founded in 2015, we have grown to over 800 employees across three continents, serving more than 200 enterprise customers with our flagship product, OrbitView — a real-time observability dashboard that processes over 50 billion data points daily. Our mission is to make complex infrastructure data accessible, actionable, and beautiful.\n\nAs a Senior React Developer, you will lead the architecture and development of OrbitView\'s frontend, which serves thousands of internal users across DevOps, SRE, and engineering teams. You will work within a cross-functional squad of 8 engineers (frontend, backend, QA, and design) that follows Scrum with two-week sprints. Your team collaborates closely with product managers, backend engineers, and UX designers to deliver a seamless, high-performance user experience.\n\nOur frontend stack is built on React 18 with TypeScript 5.3, Redux Toolkit 2.0 for state management, and Tailwind CSS 3.4 for styling. We use Webpack 5 with Module Federation for micro-frontend decomposition, React Query (TanStack Query v5) for server state management, and Vitest with React Testing Library for unit and integration testing. Our CI/CD pipeline runs on GitHub Actions with automated visual regression testing via Percy.\n\nYou will tackle concrete technical challenges including optimizing rendering performance for real-time data streams with 50+ WebSocket connections per session, implementing virtualized lists for log data exceeding 100,000 rows, building complex data visualization components on top of D3.js and ECharts, and designing a pluggable widget system that allows teams to compose custom dashboards. Accessibility compliance (WCAG 2.1 AA) is a non-negotiable requirement for all UI components we ship.\n\nSuccess is measured by key metrics including page load times under 2 seconds at the 95th percentile, Time to Interactive under 1.5 seconds, Lighthouse performance scores above 90, and customer satisfaction scores above 4.5 out of 5 in quarterly surveys. Growth opportunities include leading the frontend guild of 25+ developers, contributing to our open-source component library, and driving our design system evolution across all product lines.\n\nThe business impact of this role is significant. OrbitView generates over $40 million in annual recurring revenue, and improvements to the frontend experience directly affect user adoption, retention, and expansion. Our users spend an average of 6 hours daily in the platform, making every performance optimization and UX improvement multiply across thousands of users — directly contributing to customer satisfaction and revenue retention.',
          requirements: '5+ years of professional experience building complex single-page applications with React\nProduction experience with React 18 concurrent features including Suspense and transitions\nDeep understanding of React hooks, custom hooks patterns, and component lifecycle optimization\nStrong proficiency in TypeScript 5.x with generics, utility types, and conditional types\nExperience with Redux Toolkit including createAsyncThunk, createSlice, and RTK Query\nExpert-level CSS skills with Tailwind CSS, CSS Grid, Flexbox, and CSS-in-JS solutions\nExperience implementing micro-frontend architecture using Webpack 5 Module Federation\nProficiency with testing frameworks: Jest, React Testing Library, Vitest, and Cypress for E2E testing\nDemonstrated ability to optimize web performance: code splitting, lazy loading, memoization, and bundle analysis using Webpack Bundle Analyzer\nExperience building real-time UIs with WebSockets, Server-Sent Events, or GraphQL subscriptions\nFamiliarity with WCAG 2.1 AA accessibility standards and ARIA design patterns\nExperience with version control (Git) and CI/CD pipelines including automated testing gates\nStrong understanding of security best practices for frontend applications including XSS, CSRF, and CSP\nExperience mentoring 2+ junior developers and conducting thorough code reviews weekly\nExcellent cross-functional communication skills with experience presenting technical decisions to stakeholders\nBachelor\'s degree in Computer Science, Engineering, or equivalent practical experience',
          benefits: 'Competitive salary with annual performance bonuses up to 20% of base salary\nComprehensive health insurance covering self, spouse, parents, and children up to ₹10,00,000 per annum\nEmployee Stock Option Plan (ESOP) with 4-year vesting and early exercise option\nGenerous PF and gratuity contributions as per company policy\nFlexible hybrid work model with 3 days in-office and 2 days remote each week\nAnnual learning and development budget of ₹1,50,000 for courses, conferences, and certifications\n28 paid leave days annually plus 12 public holidays\nFree lunch, unlimited snacks, coffee, and beverages at the Bangalore office\nGym and wellness program membership worth ₹30,000 annually\nRegular team offsites and quarterly hackathons with prize pools up to ₹1,00,000\nHome office setup allowance of ₹50,000 for remote work equipment\nMonthly mobile and internet reimbursement of ₹2,000\nEmployee assistance program with 24/7 mental health and financial counseling\nRelocation assistance of ₹1,00,000 for candidates moving to Bangalore\nParental leave: 6 months paid maternity leave and 1 month paid paternity leave\nRecognition program with quarterly spot bonuses and annual awards gala',
          skills_required: 'React, TypeScript, Redux, JavaScript, CSS, HTML, Jest, Git, Webpack',
          is_featured: 1
        },
        {
          title: 'Backend Node.js Engineer',
          company: 'TechCorp Inc.',
          location: 'Remote (India)',
          type: 'Full-time',
          experience_level: 'Mid-Level',
          salary: '₹93,50,000 - ₹1,19,00,000 / year',
          description: 'TechCorp Inc. is a Bangalore-headquartered enterprise SaaS company that builds infrastructure monitoring and observability platforms. Our flagship product, OrbitView, processes over 50 billion data points daily for 200+ enterprise customers including several Fortune 500 companies. Our backend infrastructure team is responsible for the data ingestion pipelines, real-time processing engines, and the RESTful APIs that power the entire platform.\n\nAs a Backend Node.js Engineer on our distributed infrastructure team of 15 engineers across 4 squads, you will design, build, and maintain highly scalable microservices that handle over 500,000 requests per minute. You will work in an agile environment with two-week sprints, daily standups, and weekly demos. Your squad focuses on the data ingestion and processing layer — the backbone of our platform\'s real-time capabilities.\n\nOur backend stack runs on Node.js 20 with Express 4.18, TypeScript 5.3, PostgreSQL 16 with TimescaleDB extension for time-series data, Redis 7 for caching and pub/sub, RabbitMQ 3.12 for async message processing, and Docker with AWS ECS Fargate for container orchestration. We use Prisma ORM for database access and Zod for runtime type validation. All code is deployed via GitHub Actions CI/CD pipelines with automated canary deployments.\n\nYou will solve challenging engineering problems including building a horizontally scalable data ingestion system that handles 1 million+ events per second, implementing idempotent API endpoints for reliable financial data processing, optimizing PostgreSQL queries to maintain sub-10ms response times at the 99th percentile, designing a dead-letter queue and retry mechanism for fault-tolerant message processing, and building an internal developer portal with real-time service health monitoring.\n\nKey success metrics include API response times at the 99th percentile under 50ms, service uptime of 99.99%, error budgets within SLO targets, and successful onboarding of new data sources within agreed timelines. Growth opportunities include becoming the technical lead for your squad, contributing to our open-source monitoring tools, and driving architectural decisions for the next generation of our data pipeline platform.\n\nThe business impact is direct and measurable: every millisecond of latency reduction in our APIs translates to faster dashboard load times for customers, which correlates with higher user engagement and lower churn rates. Your work on the data ingestion pipeline determines our ability to onboard new enterprise customers, directly affecting our $40M+ ARR growth trajectory and market expansion plans.',
          requirements: '3+ years of production experience building Node.js applications serving production traffic\nStrong proficiency with Express.js 4.x or Fastify with TypeScript\nDeep understanding of PostgreSQL including query optimization using EXPLAIN ANALYZE, indexing strategies, and migration management with Prisma or Knex\nExperience designing RESTful APIs following OpenAPI 3.0 specification with versioning strategies\nProduction experience with message queue systems (RabbitMQ 3.x, BullMQ, or Amazon SQS)\nHands-on experience with Docker containerization and Docker Compose for multi-service local development\nWorking knowledge of Redis 6+ for caching patterns, rate limiting, distributed locks, and session management\nExperience building microservices with inter-service communication patterns (HTTP, gRPC, or event-driven with Kafka)\nProficiency with Git and collaborative development workflows (feature branches, pull request reviews, rebasing)\nStrong debugging skills including distributed tracing with OpenTelemetry and centralized log analysis\nExperience writing automated tests: unit tests with Jest, integration tests with Supertest, and contract tests\nFamiliarity with AWS services: ECS, RDS, ElastiCache, SQS, CloudWatch, and IAM roles\nUnderstanding of API security best practices: OAuth2, JWT authentication, rate limiting, input validation with Zod\nExperience with CI/CD pipelines (GitHub Actions or GitLab CI) and blue-green deployment strategies\nExcellent written communication skills for async remote collaboration across Indian time zones\nBachelor\'s degree in Computer Science or equivalent professional experience with 4+ years in backend roles',
          benefits: '100% remote work flexibility from anywhere in India with full-time employment benefits\nAnnual learning stipend of ₹1,00,000 for courses, conferences, and certifications\nComprehensive health insurance covering self, spouse, and children up to ₹8,00,000 per annum\nQuarterly performance bonuses of 10-15% of base salary based on team and individual metrics\n24 paid leave days annually plus flexible sick leave policy with no doctor\'s note required\nHome office setup budget of ₹50,000 for ergonomic chair, desk, monitor, and accessories\nMonthly internet and electricity allowance of ₹3,000 deposited directly to your account\nEmployee wellness program including 12 free mental health counseling sessions per year\nAnnual company retreat at a destination location within India fully covered\nOpportunity to attend and speak at international tech conferences with full travel sponsorship\nStock option grants with 4-year vesting schedule and early exercise window\nFree access to premium learning platforms including O\'Reilly, Udemy Business, and Egghead\nMonthly team social events and virtual game nights with gift vouchers\nRecognition program with quarterly peer-nominated awards and cash prizes up to ₹25,000\nSabbatical of 1 month after every 3 years of continuous service with full pay\nCareer progression framework with bi-annual promotion reviews and defined IC and management tracks',
          skills_required: 'Node.js, Express, PostgreSQL, Redis, Docker, RabbitMQ, AWS, REST APIs, Git',
          is_featured: 1
        },
        {
          title: 'Full Stack Engineer',
          company: 'Stripe Solutions',
          location: 'Mumbai, MH (On-site)',
          type: 'Contract',
          experience_level: 'Mid-Level',
          salary: '₹7,650 - ₹9,350 / hour',
          description: 'Stripe Solutions is a fast-growing fintech company headquartered in Mumbai that builds payment orchestration and subscription management platforms for Indian and Southeast Asian markets. Our platform processes over ₹500 crore in monthly transaction volume across 10,000+ merchants, handling everything from recurring billing to invoice generation and payment gateway orchestration.\n\nAs a Full Stack Engineer on our billing and payments team of 12 engineers, you will be instrumental in developing and enhancing our payment onboarding flows, subscription management systems, and invoice generation pipelines. Your squad follows agile methodologies with two-week sprints, daily standups, and regular retrospectives. You will collaborate with product managers, compliance officers, and QA engineers.\n\nOur technology stack combines React 18 with TypeScript on the frontend, Node.js 20 with NestJS 10 on the backend, PostgreSQL 15 with TypeORM for data persistence, and Redis for caching and job queues. We use Docker for local development, Kubernetes for production orchestration on AWS EKS, and Terraform for infrastructure-as-code. Our CI/CD pipeline is built on GitLab CI with automated security scanning.\n\nYou will tackle challenges including integrating with 15+ payment gateways (Razorpay, Stripe, PayU, BillDesk, etc.) each with different APIs and webhook formats, building a subscription scheduling engine that handles pro-rata billing, upgrades, downgrades, and cancellations, designing idempotent idempotency-key based APIs for financial transaction safety, implementing fraud detection rules engine for payment routing, and ensuring PCI-DSS Level 1 compliance across all data handling.\n\nSuccess metrics include payment success rate above 98%, invoice generation time under 500ms, merchant onboarding time reduced from days to hours, and zero financial reconciliation errors. Growth opportunities include leading technical architecture for new payment method integrations, contributing to our open-source payment SDK, and transitioning to a full-time engineering lead role.\n\nThe business impact is critical to our bottom line. Every percentage point improvement in payment success rate translates to ₹5 crore additional monthly transaction volume. Your work on the subscription management system directly affects our merchant retention rates, and the reliability of our billing pipeline determines customer trust and our ability to close enterprise deals with major Indian brands.',
          requirements: '4+ years of hands-on full stack development experience with production applications\nProficiency in React.js 18 with hooks, functional components, and TanStack Query for server state\nStrong Node.js skills with NestJS 10 or Express 4.x, including middleware and interceptor patterns\nExperience with SQL databases (PostgreSQL 14+ or MySQL 8) and TypeORM or Prisma ORM\nProduction experience integrating with payment gateways (Razorpay, Stripe, PayU, or BillDesk APIs)\nUnderstanding of subscription billing models including recurring payments, dunning, and invoicing workflows\nKnowledge of event-driven architecture with BullMQ or RabbitMQ for async job processing\nFamiliarity with Docker, Docker Compose, and containerized application deployment\nExperience writing unit tests (Jest) and integration tests for both frontend and backend services\nAbility to work from our Mumbai office 5 days a week with core hours 10 AM to 6 PM\nStrong attention to detail and understanding of financial data accuracy and reconciliation\nExperience with RESTful API design following OpenAPI specifications and API versioning\nFamiliarity with version control (Git) and CI/CD pipelines (GitLab CI or GitHub Actions)\nKnowledge of PCI-DSS compliance requirements and secure payment data handling practices\nExcellent debugging and problem-solving skills for diagnosing production issues across the full stack\nBachelor\'s degree in Computer Science, Information Technology, or related field',
          benefits: 'Competitive hourly rate with guaranteed minimum 40 hours per week and bi-weekly payments\nFlexible working hours with core overlap 11 AM to 4 PM for team collaboration\nAccess to premium co-working spaces in Mumbai with dedicated desk option\nOpportunity for contract extension beyond 6 months or full-time conversion based on performance\nHands-on experience with cutting-edge fintech systems processing real payment transactions\nRegular team lunches, monthly social events, and quarterly team outings in Mumbai\nProfessional development budget of ₹75,000 for certifications and conference attendance\nFree access to Stripe Solutions product suite for personal and side projects\nEquipment budget of ₹40,000 for laptop and accessories\nComprehensive accident and term life insurance coverage during contract period\nPaid sick leave of 12 days per year for contracted employees\nReferral bonus of ₹50,000 for each successfully referred engineer who completes probation\nAccess to company health checkup camps twice a year\nOpportunity to contribute to open-source fintech libraries under company sponsorship\nRegular one-on-one career coaching sessions with engineering managers\nNetworking opportunities through Stripe Solutions partner events and fintech meetups',
          skills_required: 'React, Node.js, PostgreSQL, TypeScript, Docker, Git, REST APIs, Payment Gateways',
          is_featured: 0
        },
        {
          title: 'UI/UX Designer',
          company: 'Aesthetic Labs',
          location: 'Remote (Worldwide)',
          type: 'Part-time',
          experience_level: 'Entry',
          salary: '₹34,00,000 - ₹46,75,000 / year',
          description: 'Aesthetic Labs is a design-focused product studio based in Berlin with a globally distributed team of 40 designers, developers, and product managers. We build beautiful, high-converting SaaS products for startups and mid-market companies across e-commerce, health tech, and education verticals. Our portfolio includes 12 shipped products used by over 2 million users worldwide.\n\nAs a UI/UX Designer, you will work directly with our founding team of experienced designers and product managers to shape the visual identity and user experience of our growing product suite. You will be part of a small, nimble team of 4 designers that values autonomy, creativity, and rapid iteration. Communication happens primarily through async channels with weekly sync meetings.\n\nYour responsibilities span the entire design process from user research and competitive analysis to wireframing, high-fidelity mockups, prototyping, and design handoff to developers. You will create and maintain design systems, component libraries, and brand guidelines using Figma. Our workflow follows a lean UX approach with rapid prototyping cycles and user testing every two weeks.\n\nYou will work on diverse design challenges including designing conversion-optimized landing pages that achieve 30%+ conversion rates, crafting intuitive onboarding flows that reduce time-to-value by 40%, building accessible component libraries following WCAG 2.1 AA standards, and creating data visualization dashboards that make complex analytics immediately understandable. You will conduct usability testing sessions with real users and iterate based on behavioral data.\n\nSuccess is measured by improvements in key product metrics: task completion rates, time-on-task, Net Promoter Score, and conversion funnel optimization. Growth opportunities include leading design for an entire product vertical, mentoring junior designers as we expand the team, and building a portfolio of shipped products that demonstrate measurable business impact.\n\nThe business impact of your design work is direct and measurable. Our products rely on user engagement and conversion for revenue. A well-designed onboarding flow can increase activation rates by 25%, directly translating to thousands of new active users. Your design system contributions ensure consistent, high-quality experiences across all our products, reducing development time and improving brand perception across our entire portfolio.',
          requirements: 'Proficiency in Figma including auto-layout, components, variants, interactive components, and prototyping\nA stellar portfolio showcasing 3+ web and mobile app designs with case studies showing process and outcomes\nStrong understanding of visual design principles: typography, color theory, hierarchy, spacing, and gestalt principles\nKnowledge of UX research methodologies including user interviews, surveys, usability testing, and A/B testing\nExperience creating and maintaining design systems and component libraries using Figma Styles and components\nFamiliarity with responsive design principles and mobile-first approach across breakpoints\nBasic understanding of HTML, CSS, and JavaScript limitations to facilitate effective developer handoff\nExcellent communication skills for presenting and defending design decisions in written and verbal formats\nAbility to work independently with minimal supervision in an async environment across time zones\nEagerness to learn from feedback and incorporate constructive critique into design iterations\nExperience with prototyping tools for micro-interactions and motion design (Principle, After Effects, or Lottie)\nKnowledge of accessibility best practices including color contrast ratios, focus states, and screen reader compatibility\nFamiliarity with design handoff tools (Zeplin, Figma Dev Mode, or Avocode)\nBasic understanding of design sprint methodology and rapid prototyping techniques\nExperience with user persona creation, journey mapping, and information architecture\nPortfolio demonstrating data-driven design decisions and measurable outcomes from previous projects',
          benefits: 'Work from anywhere in the world with flexible 20-hour weeks and your own schedule\nHighly creative freedom with ownership of product design direction across multiple products\nAccess to premium design tools and resources including Figma, Adobe Creative Cloud, and Maze\nRegular design critique sessions with senior designers from top companies including Google and Airbnb\nOpportunity to build a strong portfolio with real-world shipped products used by millions\nFlexible schedule with no fixed working hours — choose your own schedule within async framework\nStipend of ₹60,000 for design courses, conferences, and workshops annually\nPotential to transition to full-time role based on performance and company growth\nMonthly internet and co-working space allowance of ₹5,000\nAnnual design conference ticket and travel budget of ₹1,50,000\nAccess to company Figma component library and design token system\nOpportunity to contribute to our open-source design system used by the community\nQuarterly design book budget with team book club discussions\nEquipment budget of ₹80,000 for a high-resolution monitor, tablet, and design peripherals\nTwo-week annual team retreat at inspiring locations with travel and accommodation covered\nDirect portfolio mentorship from the founding team to help you advance your career',
          skills_required: 'Figma, UI Design, UX Research, Prototyping, Design Systems, Wireframing, Visual Design',
          is_featured: 1
        },
        {
          title: 'Machine Learning Engineer',
          company: 'AI Dynamics',
          location: 'Hyderabad, TS',
          type: 'Full-time',
          experience_level: 'Senior',
          salary: '₹1,19,00,000 - ₹1,53,00,000 / year',
          description: 'AI Dynamics is a Hyderabad-based artificial intelligence company that builds intelligent automation platforms for enterprise customers in finance, healthcare, and logistics. Founded by alumni of IIT Hyderabad and Stanford, we have grown to 300+ employees with offices in Hyderabad, San Francisco, and London. Our platform automates complex document processing workflows for 50+ enterprise clients.\n\nAs a Senior Machine Learning Engineer, you will design, develop, and deploy state-of-the-art predictive models that power our intelligent document processing platform. You will join a team of 20 ML engineers and data scientists organized into 3 squads focused on NLP, computer vision, and recommendation systems. You will report to the Director of ML and collaborate with product managers, data engineers, and domain experts.\n\nOur ML infrastructure runs on AWS SageMaker for model training, Kubernetes (EKS) for model serving, and on-premise GPU clusters with NVIDIA A100s for research workloads. We work with Python 3.12, PyTorch 2.1, TensorFlow 2.15, Hugging Face Transformers 4.36, and our MLOps stack includes MLflow 2.8 for experiment tracking, Weights & Biases for visualization, and Feast for feature store management.\n\nYou will tackle challenging problems including fine-tuning large language models (LLMs) for domain-specific document extraction with 99%+ accuracy, building multi-modal models that process text, tables, and images simultaneously, designing real-time inference pipelines with sub-100ms latency for interactive document processing, implementing active learning loops to reduce human annotation effort by 70%, and deploying models to production with automated A/B testing and rollback capabilities.\n\nSuccess metrics include model accuracy exceeding 99% on held-out test sets, inference latency under 100ms at the 99th percentile, model training time reduced by 50% through distributed training optimization, and successful deployment of 10+ models to production per quarter. Growth opportunities include publishing research at top conferences (NeurIPS, ICML, CVPR), leading a squad of 4-5 ML engineers, and driving our LLM strategy for the next generation of our platform.\n\nThe business impact is transformative. Our document processing platform saves enterprise clients an average of 10,000 person-hours per month. Every percentage point improvement in extraction accuracy reduces manual review costs by ₹2 crore annually for our largest clients. Your models directly determine whether our platform can expand into new verticals like legal document processing and medical records management — representing a ₹200 crore addressable market expansion.',
          requirements: '5+ years of hands-on machine learning engineering experience deploying models to production\nStrong proficiency in Python 3.x with numpy, pandas, scikit-learn, and scientific Python ecosystem\nDeep experience with deep learning frameworks: PyTorch 2.x or TensorFlow 2.x with custom training loops\nStrong understanding of SQL and experience working with large-scale datasets (100GB+) using PySpark or Dask\nExperience deploying ML models to production using Docker, Kubernetes, and cloud ML platforms (SageMaker or Vertex AI)\nKnowledge of ML experimentation and tracking tools: MLflow, Weights & Biases, or Neptune.ai\nFamiliarity with feature stores (Feast or Tecton) and model registries for governance\nExperience with A/B testing frameworks and statistical methods for model evaluation in production\nDeep understanding of NLP techniques including Transformers, BERT/GPT architectures, embeddings, and fine-tuning\nUnderstanding of MLOps best practices including CI/CD for ML pipelines with automated model validation gates\nExperience with distributed training using PyTorch DDP, Horovod, or Ray Train\nKnowledge of model monitoring, drift detection, and automated retraining pipelines in production\nStrong publication record at top-tier ML conferences (NeurIPS, ICML, CVPR, ACL, EMICLR) is a strong plus\nMaster\'s or PhD in Computer Science, Machine Learning, or related quantitative field\nExperience leading ML projects from research through development to production deployment\nProficiency with version control (Git), code review practices, and reproducible research workflows',
          benefits: 'Top-of-market salary with annual equity refresh grants worth ₹50,00,000 over 4 years\nComprehensive health insurance covering self, spouse, parents, and children up to ₹15,00,000 per annum\nUnlimited paid time off policy with mandatory minimum 20 days taken per year\nAnnual conference attendance budget of ₹2,00,000 including travel and accommodation\nGPU access for personal research projects on our A100 cluster during off-peak hours\nWeekly catered lunches and fully stocked kitchen at Hyderabad office\nRelocation assistance of ₹2,00,000 for moving to Hyderabad including temporary housing for 1 month\nSabbatical policy of 2 months paid leave after every 4 years of continuous service\nWellness program with premium gym membership ₹40,000 and mental health support\nPatent filing incentives of ₹50,000 per filed patent and ₹2,00,000 per granted patent\nAnnual compute budget of ₹1,00,000 for personal ML experiments on cloud platforms\nFree access to all major ML research papers through institutional subscriptions\nQuarterly team offsites to hill stations or beach destinations for strategy and bonding\nStock option buyback program for vested shares every year\nOn-site childcare facility and flexible parental leave policy\nAccess to exclusive AI Dynamics alumni network and ongoing career support',
          skills_required: 'Python, PyTorch, TensorFlow, SQL, Docker, Kubernetes, AWS, NLP, MLflow',
          is_featured: 1
        },
        {
          title: 'DevOps Specialist',
          company: 'CloudNet',
          location: 'Remote (India)',
          type: 'Contract',
          experience_level: 'Mid-Level',
          salary: '₹6,800 - ₹8,500 / hour',
          description: 'CloudNet is a cloud infrastructure consulting and managed services company based in Bangalore, serving 100+ clients across fintech, e-commerce, and SaaS verticals. We design, build, and operate cloud-native infrastructure for companies that need 99.99% uptime and global scalability. Our team of 80 engineers manages over 500 Kubernetes clusters across AWS, GCP, and Azure.\n\nAs a DevOps Specialist, you will maintain and optimize our Kubernetes-based infrastructure that supports over 200 microservices across multiple cloud providers for several enterprise clients simultaneously. You will join our infrastructure team of 15 engineers, working in a pod structure with 3-4 engineers per client account. You will participate in weekly on-call rotations and incident review meetings.\n\nYour day-to-day work involves managing Kubernetes clusters (EKS, GKE, AKS), improving CI/CD pipelines with ArgoCD and GitHub Actions, implementing infrastructure-as-code using Terraform and Pulumi, monitoring system health with Prometheus and Grafana, and responding to incidents using PagerDuty. Our observability stack includes the ELK stack for logs, Jaeger for distributed tracing, and Datadog for APM.\n\nYou will tackle concrete infrastructure challenges including designing multi-region Kubernetes clusters with active-active failover for disaster recovery, implementing cluster auto-scaling strategies that reduce cloud spend by 30% while maintaining performance, building GitOps workflows with ArgoCD that enable zero-downtime deployments across 200+ services, creating cost optimization dashboards that identify savings opportunities across cloud providers, and automating compliance checks for SOC 2, ISO 27001, and PCI-DSS standards.\n\nSuccess metrics include cluster uptime of 99.99%, deployment frequency increased to 50+ per day, mean time to recovery under 15 minutes, and cloud cost reduction of 20% year-over-year. Growth opportunities include leading infrastructure for our largest enterprise accounts, developing internal tools and automation frameworks used across the company, and earning advanced cloud certifications fully sponsored.\n\nThe business impact is foundational to our client relationships. Our clients trust us with their most critical infrastructure — an e-commerce client processes ₹100 crore daily through clusters we manage. Every minute of downtime costs them ₹70,000 in lost revenue. Your work ensuring reliability, security, and cost-efficiency directly determines client retention (currently 95%) and our ability to win new accounts through case studies and references.',
          requirements: '3+ years of experience in DevOps or Site Reliability Engineering roles managing production infrastructure\nStrong expertise with Kubernetes (EKS, GKE, or AKS) in production environments with 50+ nodes\nDeep knowledge of Docker containerization, image optimization, and multi-stage builds\nExperience with infrastructure-as-code tools: Terraform 1.5+ or Pulumi for cloud resource management\nProficiency with CI/CD tools: GitHub Actions, GitLab CI, ArgoCD, or Jenkins with pipeline-as-code\nStrong scripting skills in Bash and Python for automation and tooling\nExperience with monitoring and observability: Prometheus, Grafana, Loki, and alerting with Alertmanager\nKnowledge of cloud networking: VPC design, load balancers, DNS (Route53/Cloud DNS), CDN, and VPN\nExperience with incident response, on-call rotations, and post-mortem analysis using blameless culture\nUnderstanding of security best practices: IAM roles, network policies, secrets management (Vault), and pod security\nExperience with log management and analysis using ELK Stack (Elasticsearch, Logstash, Kibana) or Loki\nFamiliarity with distributed tracing tools (Jaeger, OpenTelemetry) for microservice debugging\nExperience with cost optimization: reserved instances, spot instances, and right-sizing recommendations\nKnowledge of GitOps principles and tools: ArgoCD, Flux, or Rancher Fleet for declarative deployments\nExcellent troubleshooting and root cause analysis skills with systematic debugging approach\nCertification in Kubernetes (CKA or CKAD) or cloud platform (AWS SA, GCP PCA, Azure AZ-104) preferred',
          benefits: 'Competitive hourly rate with guaranteed 40 hours per week and bi-weekly payments\nFully remote work with flexible scheduling across Indian time zones\nAccess to CloudNet\'s learning platform with 500+ cloud and DevOps courses\nOpportunity to work with cutting-edge cloud native technologies across multiple cloud providers\nParticipation in on-call rotations with additional compensation of ₹2,000 per on-call day\nQuarterly team meetups at various Indian destinations with all expenses covered\nCertification reimbursement for AWS, GCP, Azure, or CKA exams with ₹50,000 annual budget\nPotential for 12-month contract renewal and long-term engagement with career progression\nEquipment budget of ₹60,000 for home office setup including networking gear\nMonthly internet allowance of ₹2,500 for high-speed broadband connection\nAccess to CloudNet\'s internal tooling and automation frameworks for personal learning\nOpportunity to contribute to open-source CNCF projects during work hours\nQuarterly performance bonus of up to 10% of quarterly earnings\nHealth insurance coverage for self and family during contract tenure\nReferral bonus of ₹40,000 per successful candidate referral\nAccess to exclusive DevOps community events, webinars, and industry conferences',
          skills_required: 'Kubernetes, Docker, Terraform, AWS, CI/CD, Prometheus, Grafana, Python, Bash',
          is_featured: 0
        },
        {
          title: 'Frontend Developer (Vue.js)',
          company: 'VueMastery',
          location: 'Gurgaon, HR (Hybrid)',
          type: 'Full-time',
          experience_level: 'Mid-Level',
          salary: '₹64,20,000 - ₹85,60,000 / year',
          description: 'VueMastery is a Gurgaon-based edtech company that operates one of the world\'s largest online learning platforms for Vue.js developers. With over 100,000 active learners, 500+ video courses, and interactive coding exercises, we help developers master modern frontend development. Our platform has a 4.8-star rating on G2 and is trusted by engineering teams at Google, Microsoft, and Amazon for team training.\n\nAs a Frontend Developer, you will build engaging, performant user interfaces for our educational platform. You will join a product team of 12 engineers, designers, and content creators organized into two squads: Platform (core features) and Content (course player and exercises). Your squad follows Scrum with two-week sprints, daily standups, and bi-weekly retrospectives.\n\nYou will work extensively with Vue 3.4 Composition API, Pinia 2.1 for state management, Vite 5 for build tooling, and Vitest 1.2 for testing. We maintain a custom component library built on Nuxt 3.9 that powers both our main platform and marketing site. Our stack includes TypeScript 5.3, SCSS modules, Apollo Client 3.9 for GraphQL, and Storybook 7.6 for component documentation.\n\nYou will tackle challenges including building an interactive code playground with real-time execution that supports 10+ programming languages, implementing a video streaming interface with bookmarks, speed controls, and transcript search, designing a gamification system with progress tracking and certification workflows, optimizing the course player for low-bandwidth environments in emerging markets, and creating an instructor dashboard with analytics on learner engagement and course completion rates.\n\nSuccess metrics include page load times under 1.5 seconds, course completion rates above 65%, user engagement time over 30 minutes per session, and accessibility score of 95+ on automated audits. Growth opportunities include leading frontend architecture decisions for new product features, mentoring junior developers joining the team, and contributing to our open-source UI component library used by 5,000+ developers.\n\nThe business impact is directly tied to learner outcomes. Every improvement in page load speed correlates with a 2% increase in course completion rates. The interactive coding exercises you build are our primary differentiator from competitors — learners who complete 10+ exercises are 3x more likely to subscribe annually. Your work on the platform experience directly drives our $15M ARR growth and learner retention metrics.',
          requirements: '3+ years of frontend development experience with at least 2 years focused on Vue.js ecosystem\nDeep understanding of Vue 3 Composition API, reactivity system, lifecycle hooks, and Teleport/Suspense features\nProficiency with TypeScript 5.x including generics, composition functions with type safety, and tsconfig optimization\nExperience with Pinia or Vuex for centralized state management with modular stores\nStrong knowledge of SCSS, CSS animations, responsive design, and modern CSS features (container queries, layers)\nExperience with unit testing (Vitest, Jest) and E2E testing (Cypress 12+, Playwright) for Vue components\nFamiliarity with Nuxt 3 including server-side rendering, static generation, and hybrid rendering modes\nKnowledge of web accessibility (WCAG 2.1 AA/AAA) standards and hands-on experience with screen reader testing\nExperience with GraphQL clients (Apollo Client or Urql) for efficient data fetching and caching\nGood eye for design and pixel-perfect attention to detail in UI implementation from Figma mockups\nExperience with Storybook for component development, documentation, and visual regression testing\nFamiliarity with monorepo tooling (Turborepo, Nx, or pnpm workspaces) for multi-package projects\nExperience with performance profiling using Chrome DevTools, Lighthouse CI, and WebPageTest\nStrong communication skills for collaborating in a hybrid environment with async documentation\nExperience building and maintaining design systems and reusable component libraries\nBachelor\'s degree in Computer Science, Design, or equivalent practical experience with portfolio',
          benefits: 'Competitive salary with bi-annual performance reviews and raises of 10-15%\nPrivate health insurance with dental and vision coverage up to ₹7,00,000 per annum\nComplimentary gym membership at a premium fitness center near Gurgaon office worth ₹25,000 annually\nFlexible hybrid schedule with 2 days in-office and 3 days remote each week\nAnnual learning budget of ₹1,00,000 for courses, conferences, and certifications\nMonthly team outings and quarterly hackathons with prizes up to ₹50,000\nFree access to all VueMastery courses, premium content, and certification exams\n28 paid leave days annually plus 12 sick days and 3 personal days\nParental leave policy with 6 months paid maternity leave and 1 month paid paternity leave\nEmployee assistance program for mental health counseling and financial advisory services\nHome office allowance of ₹40,000 for setting up your remote workspace\nMonthly internet reimbursement of ₹1,500\nStock option grants for all full-time employees with 4-year vesting schedule\nAnnual team retreat at a domestic or international destination fully covered\nRecognition program with employee of the quarter awards and cash bonus of ₹30,000\nCareer progression framework with defined IC levels and engineering management track',
          skills_required: 'Vue.js, TypeScript, SCSS, Nuxt, Vite, Pinia, Vitest, Cypress, GraphQL, Git',
          is_featured: 0
        },
        {
          title: 'Data Scientist',
          company: 'QuantCorp',
          location: 'Pune, MH',
          type: 'Full-time',
          experience_level: 'Entry',
          salary: '₹72,25,000 - ₹89,25,000 / year',
          description: 'QuantCorp is a Pune-based quantitative analytics and financial technology company that builds data-driven decision-making platforms for asset management firms, banks, and insurance companies. Founded in 2018, we have grown to 150 employees serving 30+ financial institutions. Our platform analyzes terabytes of market data daily to generate actionable insights for portfolio managers.\n\nAs an Entry-Level Data Scientist, you will join our analytics team of 10 data scientists and work under the guidance of senior mentors. You will analyze user behavior data, financial metrics, and operational KPIs using SQL, Python, and modern BI tools. Our team follows a structured 3-month onboarding program with weekly mentoring sessions, gradually increasing your ownership from guided analysis to independent projects.\n\nYou will work with our data stack including PostgreSQL 15, Snowflake for data warehousing, dbt for data transformation, Python 3.12 with pandas 2.1, numpy 1.26, and scikit-learn 1.3, and visualization tools including Tableau 2023 and Metabase. Our ML pipeline runs on AWS SageMaker with experiment tracking via MLflow. We use Git for version control and follow code review practices for all analysis and models.\n\nYou will tackle diverse analytical challenges including building predictive models for customer churn that identify at-risk clients 30 days in advance, designing A/B testing frameworks for product feature launches with proper statistical power analysis, creating automated KPI dashboards that alert stakeholders to significant metric movements, analyzing user behavior funnels to identify optimization opportunities in the product onboarding flow, and developing regression models to forecast revenue growth based on market indicators.\n\nSuccess metrics for your first year include independently running 2+ end-to-end analysis projects from data extraction through presentation, building 3+ production dashboards used by executive stakeholders, achieving mentor sign-off on your analysis methodology and code quality, and contributing to at least one cross-functional team project. Growth opportunities include specializing in financial modeling, leading junior analysts in your second year, and pursuing advanced certifications sponsored by the company.\n\nThe business impact of data science at QuantCorp is central to our value proposition. Our clients make investment decisions worth billions based on insights generated by our platform. The churn models you build directly protect ₹5 crore in annual recurring revenue. The dashboards and analyses you create enable our product team to make data-informed decisions that improve user engagement by 15% year-over-year.',
          requirements: 'Bachelor\'s or Master\'s degree in Data Science, Statistics, Computer Science, Mathematics, or related quantitative field\nStrong proficiency in SQL for data extraction, transformation, and analysis across multiple tables with complex joins\nProgramming experience in Python with pandas, numpy, and matplotlib for data manipulation and visualization\nUnderstanding of statistical concepts: hypothesis testing, p-values, confidence intervals, regression, and probability distributions\nExperience creating dashboards and visualizations using Tableau, Power BI, Metabase, or similar BI tools\nFamiliarity with basic machine learning algorithms: linear regression, logistic regression, decision trees, random forests, and clustering (KMeans, DBSCAN)\nKnowledge of A/B testing methodology including sample size calculation, randomization, and statistical significance interpretation\nStrong analytical thinking and problem-solving skills with meticulous attention to data quality and accuracy\nExcellent written and verbal communication skills for presenting technical findings to non-technical stakeholders\nAbility to work from our Pune office 5 days a week during the initial 3-month onboarding period\nFamiliarity with version control (Git) for collaborative analysis workflows and code review\nBasic understanding of financial concepts and market data is a plus but not required\nExperience with data pipeline tools (dbt, Airflow, or Prefect) is desirable\nKnowledge of experimental design including confounding variables, randomization, and blocking\nPortfolio of data science projects on GitHub or Kaggle demonstrating practical application of concepts\nGraduation with minimum 60% aggregate marks from a recognized university (freshers welcome to apply)',
          benefits: 'Structured 3-month onboarding and mentorship program with weekly 1:1 mentoring sessions\nLearning budget of ₹75,000 for courses, books, certifications, and conference attendance\nRemote work every Friday with core hours 11 AM to 4 PM\nComprehensive health insurance covering self and family up to ₹5,00,000 per annum\n24 paid leave days annually plus 12 public holidays\nRegular knowledge-sharing sessions, internal tech talks, and journal club meetings\nOpportunity to work on cross-functional projects with product, engineering, and business teams\nClear career progression framework with quarterly check-ins and bi-annual promotion reviews\nEmployee recognition program with quarterly spot bonuses of ₹15,000\nFree parking and transportation allowance of ₹3,000 per month\nAccess to premium data science learning platforms (DataCamp, Kaggle Learn, Coursera)\nCompany-sponsored participation in data science hackathons and competitions\nMonthly team lunch and quarterly team outings in and around Pune\nErgonomic workstation setup with standing desk and dual monitors at the office\nCertification bonus of ₹20,000 for completing relevant data science certifications\nOpportunity to publish research and present at internal and external conferences with travel sponsorship',
          skills_required: 'Python, SQL, Pandas, NumPy, Tableau, Machine Learning, Statistics, A/B Testing',
          is_featured: 0
        },
        {
          title: 'Product Manager',
          company: 'InnovateX',
          location: 'Bangalore, KA',
          type: 'Full-time',
          experience_level: 'Lead',
          salary: '₹1,10,50,000 - ₹1,36,00,000 / year',
          description: 'InnovateX is a Bangalore-based B2B SaaS company that builds workflow automation and analytics platforms for enterprise operations teams. Our flagship product, FlowMatrix, is used by 500+ companies including 50 Fortune 500 firms to automate complex business processes, reducing manual work by an average of 60%. We have grown to 600 employees with $80M in Series C funding from top-tier VC firms.\n\nAs a Lead Product Manager, you will own the product lifecycle for our flagship FlowMatrix platform from conception through launch and iteration. You will lead a cross-functional product team of 3 engineers, 2 designers, and a data analyst, working closely with engineering, marketing, sales, and customer success teams. You will report to the VP of Product and collaborate with other PMs on cross-product initiatives.\n\nYour workflow includes conducting weekly customer discovery interviews, maintaining a prioritized roadmap in Notion, writing detailed product requirement documents, leading sprint planning and retrospectives, analyzing product usage data in Mixpanel and Amplitude, and presenting quarterly product reviews to leadership. Our product development follows Shape Up methodology with 6-week cycles.\n\nYou will tackle challenges including defining the roadmap for our AI-powered workflow builder that reduces process creation time from weeks to hours, designing a marketplace for third-party integrations targeting 100+ connectors in the first year, leading pricing and packaging changes to launch a self-serve tier that doubles our addressable market, improving onboarding completion rates from 40% to 70% through iterative UX improvements, and defining success metrics for our enterprise SSO and compliance features required for Fortune 500 deals.\n\nSuccess is measured by North Star metrics: monthly active users growing 30% YoY, net revenue retention above 120%, time-to-value for new customers under 14 days, and NPS score above 60. Growth opportunities include scaling to lead a product vertical with multiple PMs, representing InnovateX at industry conferences as a thought leader, and progressing to Director of Product within 3 years.\n\nThe business impact is enormous. The $80M revenue target for this fiscal year depends on the product improvements you drive. Every percentage point improvement in onboarding completion adds ₹2 crore in annual revenue from reduced churn. Your decisions on feature prioritization directly affect the sales team\'s ability to close $5M+ enterprise deals. The integration marketplace you launch will open a new $20M ARR stream.',
          requirements: '6+ years of product management experience with at least 2 years in a senior or lead role with direct reports\nPrior engineering background with a Computer Science degree or equivalent technical experience building software products\nProven track record of shipping successful B2B SaaS products that achieved product-market fit and revenue growth\nDeep understanding of agile methodologies (Scrum, Shape Up, Kanban) and tools (JIRA, Notion, Linear)\nStrong analytical skills with hands-on experience using data to drive decisions: SQL, Mixpanel, Amplitude, or Heap\nExcellent stakeholder management and cross-functional leadership abilities across engineering, design, marketing, and sales\nExperience conducting user research, customer interviews, surveys, and usability testing with enterprise buyers\nKnowledge of product analytics: funnel analysis, cohort analysis, retention analysis, and product-led growth metrics\nUnderstanding of API design, platform thinking, and technical architecture trade-offs for platform products\nOutstanding written and verbal communication skills with experience presenting to C-level executives\nExperience with OKR frameworks, strategic planning, and quarterly product planning processes\nProven ability to influence without authority and drive alignment across competing priorities\nExperience with pricing and packaging strategy including tiered pricing, usage-based models, and enterprise licensing\nFamiliarity with competitive analysis and market research methodologies for B2B SaaS markets\nExperience mentoring and developing junior product managers through structured coaching and feedback\nMBA from a top-tier institution is preferred but not required with equivalent experience',
          benefits: 'Competitive salary with significant equity compensation package worth ₹60,00,000 over 4 years\nFull family health insurance including parents and in-laws up to ₹12,00,000 per annum\nGenerous ESOP pool with early exercise options and tax-efficient structure\nAnnual performance bonus of 15-25% of base salary paid quarterly and annually\n28 paid leave days annually plus flexible holiday policy with carry-forward option\nAnnual product conference budget of ₹2,00,000 including travel and accommodation\nSabbatical of 2 months paid leave after every 4 years of continuous service\nRelocation support of ₹1,50,000 for moving to Bangalore including temporary housing\nHome internet and phone allowance of ₹3,000 per month\nFree access to premium product management tools and resources worth ₹50,000 annually\nExecutive coaching and leadership development program with external coaches\nCatered lunch at the Bangalore office with unlimited snacks and beverages\nGym membership at a premium fitness center near the office worth ₹30,000 annually\nChildcare support and parental leave policy with 6 months paid leave\nAnnual team offsite for strategic planning at a resort destination fully covered\nRecognition program with quarterly innovation awards and annual Founder\'s Award of ₹1,00,000',
          skills_required: 'Product Management, Agile, JIRA, SQL, Data Analysis, UX Research, Strategy, Roadmapping',
          is_featured: 1
        },
        {
          title: 'Technical Writer',
          company: 'DocuSign',
          location: 'Remote (Global)',
          type: 'Part-time',
          experience_level: 'Mid-Level',
          salary: '₹2,550 - ₹4,250 / hour',
          description: 'DocuSign is the global leader in e-signature and agreement cloud, headquartered in San Francisco with offices worldwide. Our platform processes over 1 billion agreements annually for 1 million+ customers across 180 countries. The Developer Experience team, part of our 200-person Platform Engineering organization, creates documentation used by over 5 million developers who integrate DocuSign\'s APIs into their applications.\n\nAs a Technical Writer, you will create comprehensive, developer-friendly documentation for our public APIs and SDKs. You will join a distributed team of 15 technical writers, developers, and developer advocates spread across North America, Europe, and Asia. Your team uses an async-first communication style with daily Slack standups and weekly video syncs, allowing flexible working hours.\n\nYou will write API reference documentation, integration guides, tutorials, best practice articles, and migration guides. Our documentation is authored in Markdown, versioned with Git, and published through Docusaurus 3. We use OpenAPI 3.1 specifications as the source of truth for API documentation and maintain SDK-specific guides for JavaScript, Python, Java, .NET, and Go. You will work closely with engineering teams to understand new features and review API specifications before they ship.\n\nYou will tackle challenges including documenting complex OAuth 2.0 authorization flows with step-by-step walkthroughs for 5 different grant types, creating interactive API playgrounds that let developers test endpoints directly from documentation pages, writing migration guides from legacy SOAP APIs to modern RESTful APIs that minimize customer disruption, building a comprehensive error handling reference that covers 500+ API error codes with troubleshooting guidance, and developing onboarding documentation that reduces average integration time from 3 weeks to 5 days.\n\nSuccess metrics include documentation satisfaction scores above 4.5/5, reduction in support tickets related to documentation gaps, time-to-first-successful-API-call for new developers under 30 minutes, and community contributions to documentation via pull requests. Growth opportunities include leading documentation initiatives for major product launches, developing video tutorials and interactive learning content, and mentoring new writers joining the team.\n\nThe business impact of your work is substantial. Well-documented APIs reduce developer onboarding time, which directly accelerates sales cycles for our API products. Clear documentation reduces support costs — every well-documented feature prevents 50+ support tickets per month. Our documentation quality is frequently cited as a key factor in developers choosing DocuSign over competitors, making your work a competitive advantage worth millions in revenue.',
          requirements: '3+ years of experience in technical writing, preferably for developer-facing products and API documentation\nExcellent written English with exceptional grammar, clarity, and the ability to explain complex concepts simply\nExperience writing API documentation for REST APIs and SDKs with practical code examples\nProficiency with Markdown, Git, and documentation versioning workflows with branching and pull requests\nFamiliarity with static site generators: Docusaurus, GitBook, ReadTheDocs, or Jekyll\nAbility to understand and explain complex technical concepts to audiences ranging from junior to expert developers\nExperience reading and understanding API specifications (OpenAPI 3.x, Swagger, or GraphQL schemas)\nBasic knowledge of at least one programming language (JavaScript/TypeScript, Python, or Java) to write code samples\nStrong research skills with ability to independently gather information from engineering discussions, PRDs, and code\nPortfolio of published technical documentation samples required with at least 3 writing samples\nExperience with developer portal platforms and documentation analytics tools\nFamiliarity with docs-as-code workflow and continuous documentation deployment pipelines\nExperience creating tutorial content with step-by-step instructions and screenshots or recordings\nKnowledge of information architecture principles for organizing large documentation sites\nAbility to work independently in a remote, async environment with 20-25 hours per week availability\nExperience with accessibility standards for documentation content and screen reader compatibility',
          benefits: 'Flexible part-time schedule — work 20-25 hours per week on your own schedule with no fixed hours\nFully remote position — work from anywhere with a stable internet connection worldwide\nAccess to DocuSign\'s learning and development platform with 1000+ courses\nOpportunity to influence product design and developer experience through documentation feedback\nRegular collaboration with global engineering teams across North America, Europe, and Asia\nCompetitive hourly rate with bi-weekly payments via direct deposit\nPotential to increase hours up to 30 per week or transition to full-time role based on performance\nAnnual equipment stipend of ₹40,000 for home office setup\nMonthly coworking space allowance of ₹5,000\nFree access to all DocuSign products for personal use\nOpportunity to attend and present at developer conferences with travel coverage\nProfessional editing and peer review support to continuously improve your writing skills\nAccess to premium technical writing tools (MadCap Flare, Paligo, or similar)\nQuarterly virtual team events and annual in-person team meetup (travel covered)\nWriting portfolio development with attribution and bylines on published documentation\nReferral bonus of ₹25,000 for each successful technical writer referral',
          skills_required: 'Technical Writing, Markdown, Git, API Documentation, OpenAPI, Docusaurus, JavaScript, Python',
          is_featured: 0
        },
        {
          title: 'Cybersecurity Analyst',
          company: 'SecureNet',
          location: 'Delhi, DL',
          type: 'Full-time',
          experience_level: 'Senior',
          salary: '₹1,02,00,000 - ₹1,27,50,000 / year',
          description: 'SecureNet is a Delhi-based cybersecurity firm that provides managed security services to financial services, government, and healthcare organizations across India. Founded in 2010, we have grown to 400+ security professionals operating a 24/7 Security Operations Center (SOC) that monitors over 100,000 endpoints and protects critical infrastructure worth ₹10,000 crore.\n\nAs a Senior Cybersecurity Analyst, you will monitor, detect, and respond to security threats across our enterprise clients\' infrastructure. You will join our Tier 3 SOC team of 12 senior analysts, acting as the escalation point for complex security incidents. You will work in rotating shifts covering 24/7 operations, with additional on-call responsibility for critical incidents affecting our largest clients.\n\nOur security stack includes Splunk Enterprise Security 7.x for SIEM, CrowdStrike Falcon for EDR, Tenable for vulnerability management, Palo Alto Networks firewalls and Prisma Cloud for cloud security, and Recorded Future for threat intelligence. We follow the NIST Cybersecurity Framework and MITRE ATT&CK framework for incident classification and response. All SOC operations are ISO 27001:2022 and SOC 2 Type II certified.\n\nYou will tackle challenges including conducting advanced threat hunting across 10,000+ endpoints using behavioral analytics and IoC matching, leading incident response for ransomware attacks with containment, eradication, and recovery procedures, performing deep-dive forensic analysis of compromised systems including memory and disk forensics, assessing cloud security posture across AWS, Azure, and GCP environments for misconfigurations and compliance gaps, and developing custom detection rules and SIEM use cases that reduce mean time to detect from days to minutes.\n\nSuccess metrics include mean time to detect under 15 minutes, mean time to respond under 1 hour for critical incidents, false positive rate under 5% for detection rules, and successful completion of quarterly tabletop exercises with clients. Growth opportunities include leading the SOC team as Assistant Manager, developing specialized expertise in cloud security or digital forensics, and contributing to cybersecurity thought leadership through blog posts and conference presentations.\n\nThe business impact is critical to national infrastructure security. The financial institutions we protect process transactions worth ₹5,000 crore daily. A successful breach of one of our clients could result in losses of ₹100 crore or more. Your ability to detect and respond to threats quickly determines whether attacks succeed or fail. Every new detection rule you develop protects not just one client but the entire customer base when deployed across the SOC.',
          requirements: 'CISSP certification is mandatory — candidates without current CISSP will not be considered\n5+ years of experience in cybersecurity operations with at least 3 years in incident response roles\nDeep knowledge of SIEM platforms: Splunk Enterprise Security, QRadar, or ELK Stack with custom rule development\nExperience with endpoint detection and response tools: CrowdStrike Falcon, SentinelOne, or Microsoft Defender for Endpoint\nStrong understanding of network security: firewalls (Palo Alto, Fortinet), IDS/IPS, VPNs, and web application firewalls\nExperience conducting penetration tests and vulnerability assessments using Metasploit, Burp Suite, and Nessus\nKnowledge of cloud security: AWS Security Hub, Azure Security Center, GCP Security Command Center, and Prisma Cloud\nFamiliarity with Indian cybersecurity regulations: IT Act 2000, CERT-In guidelines, RBI cybersecurity framework, and SEBI guidelines\nExperience with threat intelligence platforms and frameworks: MITRE ATT&CK, Diamond Model, and Cyber Kill Chain\nStrong analytical and investigative skills with systematic approach to digital forensics and evidence handling\nExcellent incident report writing skills with experience creating executive summaries for C-level stakeholders\nExperience with threat hunting methodologies using both hypothesis-driven and IoC-based approaches\nKnowledge of malware analysis: static and dynamic analysis, sandboxing, and reverse engineering basics\nExperience with SOAR platforms (Splunk SOAR, Palo Alto XSOAR) for incident response automation\nFamiliarity with ISO 27001, SOC 2, PCI-DSS, and HIPAA compliance requirements and audit procedures\nBachelor\'s degree in Cybersecurity, Computer Science, or related field with relevant industry certifications',
          benefits: 'Competitive salary with quarterly performance bonuses of 10-15% of base salary\nComprehensive pension plan with employer contributions up to 12% of monthly salary\nFull family health insurance covering self, spouse, children, parents, and in-laws up to ₹12,00,000\nRemote work options up to 3 days per week with core office presence on Tuesdays and Thursdays\nAnnual certification and training budget of ₹1,50,000 including exam fees and training courses\nPaid memberships for professional organizations: ISC2, OWASP, and local cybersecurity associations\n28 paid leave days annually plus 12 sick days and 3 study leave days for exam preparation\nConference attendance budget for major security conferences: BlackHat, NullCon, BSides, and c0c0n\nSabbatical and study leave options for advanced degrees with tuition reimbursement up to ₹3,00,000\nOn-call compensation of ₹3,000 per day for after-hours incident response coverage\nAnnual equipment refresh with latest security appliances and tools for home lab setup\nCareer advancement support with structured promotion criteria and leadership development program\nEmployee wellness program with gym membership, regular health checkups, and ergonomic assessments\nAccess to SecureNet\'s internal threat intelligence feeds and research repositories\nRecognition program with quarterly Spot Award of ₹25,000 and annual Cybersecurity Excellence Award of ₹1,00,000\nReferral bonus of ₹75,000 for each successfully hired cybersecurity professional referred',
          skills_required: 'CISSP, SIEM, Penetration Testing, Network Security, Cloud Security, Incident Response, Splunk',
          is_featured: 0
        },
        {
          title: 'Mobile App Developer (Flutter)',
          company: 'AppWorks',
          location: 'Remote (India)',
          type: 'Contract',
          experience_level: 'Entry',
          salary: '₹3,400 - ₹5,100 / hour',
          description: 'AppWorks is a Pune-based mobile app development agency that builds high-quality cross-platform applications for startups and mid-market companies across e-commerce, health tech, and social networking verticals. Founded in 2019, we have shipped 30+ apps to the App Store and Google Play with a combined 5 million+ downloads. Our team of 50 engineers, designers, and QA specialists follows a client-centric delivery model.\n\nAs an Entry-Level Flutter Developer, you will help build and maintain our cross-platform mobile applications alongside senior developers. You will join a project squad of 5-6 engineers working on 2-3 client projects simultaneously. You will receive structured mentorship with weekly 1:1 sessions with a senior developer, code reviews on all your pull requests, and gradual ownership of features as you demonstrate proficiency.\n\nYou will work with Flutter 3.16, Dart 3.2, Riverpod 2.5 for state management, Dio 5.3 for HTTP networking, Firebase suite (Firestore, Authentication, Cloud Messaging, Crashlytics), and local storage with Hive and Isar. Our team uses GitLab for version control and CI/CD, and we deploy to both iOS App Store and Google Play Store through automated pipelines using Codemagic.\n\nYou will gain hands-on experience with real-world challenges including building responsive UIs that adapt to different screen sizes from phones to tablets, implementing offline-first architectures using local databases with remote sync, integrating push notifications for user engagement campaigns, handling platform-specific features like camera, GPS, biometrics, and NFC, and optimizing app performance for low-end Android devices common in the Indian market.\n\nSuccess metrics during your contract include delivering assigned features on time with fewer than 5 critical bugs per sprint, achieving 80%+ unit test coverage on code you write, receiving positive feedback from your mentor and peers during retrospectives, and demonstrating the ability to independently implement a complete screen or feature from design to deployment within 3 months.\n\nThe business impact of our apps drives our clients\' revenue. One e-commerce client generates ₹2 crore monthly through the app you will help maintain. Every crash fix, performance improvement, and feature addition contributes to user retention and conversion rates. The skills you build here apply directly to real business outcomes — your code will be used by thousands of real users, and your contributions will be part of launched, revenue-generating applications.',
          requirements: 'Foundational knowledge of Dart programming language including async/await, streams, and null safety\nUnderstanding of Flutter framework including widgets, state management, navigation, and platform channels\nExperience with REST API integration using HTTP, Dio, or similar networking packages\nBasic understanding of version control with Git including branching, commits, and pull requests\nFamiliarity with Material Design 3 guidelines and responsive UI principles for multiple screen sizes\nKnowledge of at least one state management approach: Provider, Riverpod, BLoC, or GetX with practical usage\nEagerness to learn from code reviews and incorporate feedback into subsequent work\nStrong problem-solving skills with ability to debug issues using Flutter DevTools and logging\nGood written communication skills for remote collaboration via Slack, JIRA, and GitLab\nPortfolio or GitHub repository showcasing 2+ Flutter projects (personal projects, bootcamp work, or open-source contributions)\nBasic understanding of Firebase services: Authentication, Firestore, Cloud Messaging, and Crashlytics\nFamiliarity with mobile app lifecycle: development, testing, build, and deployment to App Store and Play Store\nUnderstanding of mobile UI/UX best practices including gesture handling and animation basics\nAbility to work independently with self-directed learning and proactive communication when stuck\nAvailability for 40 hours per week with overlap of core hours 11 AM to 4 PM IST\nDiploma, Bachelor\'s degree, or equivalent bootcamp certification in Computer Science or related field',
          benefits: 'Structured mentorship program with weekly 1:1 sessions with senior developers for career guidance\nOpportunity to contribute to production apps with real users on both iOS and Android platforms\nFlexible working hours with remote-first culture and core overlap hours 11 AM to 4 PM\nLearning budget of ₹40,000 for Flutter courses, certifications, and conference tickets\nPotential for contract extension beyond 6 months and full-time conversion based on performance\nAccess to AppWorks design system, component library, and internal tools and templates\nHands-on experience with CI/CD pipelines for mobile apps using Codemagic and Fastlane\nExposure to the full mobile app development lifecycle from concept through App Store release and maintenance\nMonthly team knowledge-sharing sessions and Friday show-and-tell meetings\nCertificate of completion and detailed performance review at end of contract for portfolio use\nOpportunity to attend client meetings and understand business requirements firsthand\nEquipment stipend of ₹25,000 for development laptop or accessories\nAccess to company\'s Flutter package repository and reusable widget library\nRegular code review feedback to accelerate learning and professional growth\nNetworking opportunities with other developers in the AppWorks community\nPotential to join as a founding engineer on new client projects with equity upside for exceptional performers',
          skills_required: 'Flutter, Dart, REST APIs, Git, Provider, Material Design, Firebase, iOS, Android',
          is_featured: 1
        },
      ];

      for (const job of mockJobs) {
        await dbRun(
          `INSERT INTO jobs (employer_id, title, company_name, location, type, experience_level, salary_range, description, requirements, benefits, is_featured, skills_required)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
          [employerId, job.title, job.company, job.location, job.type, job.experience_level, job.salary, job.description, job.requirements, job.benefits, job.is_featured, job.skills_required || '']
        );
      }

      console.log('✅ Seeded database successfully with mock data.');
    } else {
      // Ensure admin user exists even on subsequent runs
      const bcrypt = require('bcryptjs');
      const existing = await dbGet('SELECT id FROM users WHERE email = $1', ['admin@antigravity.com']);
      if (!existing) {
        const adminPassword = bcrypt.hashSync('Admin123!', 10);
        await dbRun(
          `INSERT INTO users (email, password, role, name) VALUES ($1, $2, $3, $4)`,
          ['admin@antigravity.com', adminPassword, 'admin', 'Admin']
        );
        console.log('✅ Admin user created.');
      }
    }

    console.log('✅ All database tables ready.');
  } catch (error) {
    console.error('Migration error:', error.message);
    throw error;
  }
}

module.exports = {
  initDatabase,
  dbGet,
  dbAll,
  dbRun,
};
